# Generated by Django 3.1.7 on 2023-02-06 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_remove_product_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='compare_price',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
    ]
