// Authentication

export const SIGNUP_SUCCESS = 'SINGUP_SUCCESS';
export const SIGNUP_FAIL = 'SINGUP_FAIL';

export const ACTIVATION_SUCCESS = 'ACTIVATION_SUCCESS';
export const ACTIVATION_FAIL = 'ACTIVATION_FAIL';

export const SET_AUTH_LOADING = 'SET_AUTH_LOADING';
export const REMOVE_AUTH_LOADING = 'SET_AUTH_FAIL';

export const LOGIN_SUCCES = 'LOGIN_SUCCES';
export const LOGIN_FAIL = 'LOGIN_FAIL';

export const USER_LOADER_SUCCES = 'USER_LOADER_SUCCES';
export const USER_LOADER_FAIL = 'USER_LOADER_FAIL';

export const AUTHENTICATED_SUCCES = 'AUTHENTICATED_SUCCES';
export const AUTHENTICATED_FAIL = 'AUTHENTICATED_FAIL';

export const REFRESH_SUCCES = 'REFRESH_SUCCES';
export const REFRESH_FAIL = 'REFRESH_FAIL';

export const LOGOUT = 'LOGOUT';

export const RESET_PASSWORD_SUCCES = 'RESET_PASSWORD_SUCCES';
export const RESET_PASSWORD_FAIL = 'RESET_PASSWORD_FAIL';
export const RESET_PASSWORD_CONFIRM_SUCCES = 'RESET_PASSWORD_CONFIRM_SUCCES';
export const RESET_PASSWORD_CONFIRM_FAIL = 'RESET_PASSWORD_CONFIRM_FAIL';

// Alerts

export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';

// Categories

export const GET_CATEGORIES_SUCCES = 'GET_CATEGORIES_SUCCES';
export const GET_CATEGORIES_FAIL = 'GET_CATEGORIES_FAIL';

// Products

export const GET_PRODUCTS_SUCCESS = 'GET_PRODUCTS_SUCCESS';
export const GET_PRODUCTS_FAIL = 'GET_PRODUCTS_FAIL';
export const GET_PRODUCTS_BY_ARRIVAL_SUCCESS = 'GET_PRODUCTS_BY_ARRIVAL_SUCCESS';
export const GET_PRODUCTS_BY_ARRIVAL_FAIL = 'GET_PRODUCTS_BY_ARRIVAL_FAIL';
export const GET_PRODUCTS_BY_SOLD_SUCCESS = 'GET_PRODUCTS_BY_SOLD_SUCCESS';
export const GET_PRODUCTS_BY_SOLD_FAIL = 'GET_PRODUCTS_BY_SOLD_FAIL';
export const GET_PRODUCT_SUCCESS = 'GET_PRODUCT_SUCCESS';
export const GET_PRODUCT_FAIL = 'GET_PRODUCT_FAIL';
export const SEARCH_PRODUCTS_SUCCESS = 'SEARCH_PRODUCTS_SUCCESS';
export const SEARCH_PRODUCTS_FAIL = 'SEARCH_PRODUCTS_FAIL';
export const RELATED_PRODUCTS_SUCCESS = 'RELATED_PRODUCTS_SUCCESS';
export const RELATED_PRODUCTS_FAIL = 'RELATED_PRODUCTS_FAIL';
export const FILTER_PRODUCTS_SUCCESS = 'FILTER_PRODUCTS_SUCCESS';
export const FILTER_PRODUCTS_FAIL = 'FILTER_PRODUCTS_FAIL';